def build_telemetry_payload(
    job_type: str,
    cow_id: str,
    farmer_id: str,
    match_status: str,
    inference_time: float,
    final_confidence: float,
    matched_cow_id: str,
    num_crops: int,
    muzzle_url: str,
    face_url: str,
    muzzle_crop_b64: str,
    face_crop_b64: str,
    muzzle_conf: float,
    face_conf: float,
    spoof_prob_muzzle: float,
    spoof_prob_face: float,
    cow_name: str,
    face_similarity_score: float,
    muzzle_similarity_score: float,
    verdict: dict,
    matched_image_url: str,
    matched_cow_name: str,
    best_lg_matches: int,
    trad_metrics: dict,
    best_features: dict,
    xgb_score: float,
    semantic_tags: dict = None
) -> dict:
    return {
        "job_type": job_type,
        "cow_id": cow_id,
        "farmer_id": farmer_id,
        "match_status": match_status,
        "inference_time_ms": inference_time,
        "best_distance": (1.0 - final_confidence) if final_confidence > 0 else None,
        "matched_cow_id": matched_cow_id,
        "num_crops": num_crops,
        "muzzle_img_url": muzzle_url,
        "face_img_url": face_url,
        "muzzle_crop_url": muzzle_crop_b64,
        "face_crop_url": face_crop_b64,
        "muzzle_conf_m": muzzle_conf,
        "muzzle_conf_f": face_conf,
        "spoof_prob_m": spoof_prob_muzzle,
        "spoof_prob_f": spoof_prob_face,
        "cow_name": cow_name,
        "face_similarity_score": face_similarity_score,
        "muzzle_similarity_score": muzzle_similarity_score,
        "ensemble_score": final_confidence,
        "reason": verdict.get("developer_reason", verdict.get("reason", "N/A")) if verdict else "N/A",
        "best_wrong_answer_image_url": matched_image_url,
        "matched_cow_name": matched_cow_name,
        "lg_matches": (best_lg_matches if best_lg_matches != -1 else None),
        "muzzle_post_lg_score": verdict.get("muzzle_sim_post_lg") if verdict and final_confidence > 0.0 else None,
        "trad_morphology": trad_metrics.get("trad_morphology") if trad_metrics else None,
        "trad_lbp_dist": best_features.get("trad_lbp_dist") if best_features else (trad_metrics.get("trad_lbp_dist") if trad_metrics else None),
        "trad_hog_dist": best_features.get("trad_hog_dist") if best_features else (trad_metrics.get("trad_hog_dist") if trad_metrics else None),
        "trad_inlier_ratio": best_features.get("trad_inlier_ratio") if best_features else (trad_metrics.get("trad_inlier_ratio") if trad_metrics else None),
        "trad_aligned_ssim": best_features.get("trad_aligned_ssim") if best_features else (trad_metrics.get("trad_aligned_ssim") if trad_metrics else None),
        "xgb_score": xgb_score,
        "xgb_mapped_score": verdict.get("xgb_mapped") if verdict else None,
        "spatial_muzzle_sim": best_features.get("spatial_muzzle_sim") if best_features else None,
        "spatial_face_sim": best_features.get("spatial_face_sim") if best_features else None,
        "ds_belief_match": verdict.get("ds_belief_match") if verdict else None,
        "ds_belief_mismatch": verdict.get("ds_belief_mismatch") if verdict else None,
        "ds_uncertainty": verdict.get("ds_uncertainty") if verdict else None,
        "pignistic_match": verdict.get("pignistic_match") if verdict else None,
        "semantic_tags": semantic_tags
    }
